apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: color-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-storage-color
  