apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-color
  #namespace: test1
spec:
  ports:
    - port: 80
      targetPort: 8082
      #nodePort: 30202
  type: NodePort
  selector:
    app: simple-webapp-color